backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "articoli"
    label: "Articoli"
    folder: "articoli"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Contenuto", name: "body", widget: "markdown" }

  - name: "promo"
    label: "Promozioni"
    folder: "promo"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Sconto", name: "discount", widget: "string" }
      - { label: "Descrizione", name: "body", widget: "markdown" }